version: "3.9"

networks:
    app_network:
        driver: bridge
        external: true

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network
    volumes:
      - ./backend_volumes:/var/lib/backend:100M
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
  redis:
    image: "redis:latest"
    restart: always
    networks:
      - app_network
    ports:
      - "6378:6379"
    volumes:
      - redisdata:/data:50M
    command:
      - redis-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
volumes:
  redisdata:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=50m"
  backend_volumes:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=50m"
